name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      Scripts: ./.github/workflows/scripts

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Copy frontend build artifacts to dotnet app
      run: |
        mkdir -p src/QueryPressure.UI/dist
        cp -r frontend/dist/* src/QueryPressure.UI/dist/

    - name: Build and publish dotnet app
      shell: pwsh
      run: |
        ${{ env.Scripts }}/DotnetPublish.ps1 -OutputSubfolder win -Runtime win-x64
        ${{ env.Scripts }}/DotnetPublish.ps1 -OutputSubfolder linux -Runtime linux-x64
        ${{ env.Scripts }}/DotnetPublish.ps1 -OutputSubfolder osx -Runtime osx-x64
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          src/QueryPressure.UI/.out/win/QueryPressure.UI.exe
          src/QueryPressure.UI/.out/linux/QueryPressure.UI
          src/QueryPressure.UI/.out/osx/QueryPressure.UI
